#!/bin/bash

# This script is crafted specicially for the system which:
# - Running MacOS 10.8 or later
# - Having OpenCV 3.x installed
# - Having Boost installed with C++0x support

echo "Building VOSM for MacOS!"
echo "------------------------"
mkdir build
cd build

# Make with cpp, with all accessible variables printed out
cmake -DCMAKE_CXX_COMPILER=$(which g++) \
      -DCMAKE_CXX_FLAGS="-std=c++0x" \
      -DCMAKE_EXE_LINKER_FLAGS="-std=c++11 -Wl" \
      -LAH ..

make