#!/bin/bash

echo "Building VOSM for MacOS!"
echo "------------------------"
mkdir build
cd build

# Make with cpp, with all accessible variables printed out
cmake -DCMAKE_CXX_COMPILER=$(which g++) -LAH ..

make